Stale
sebastian-tk/pio_git_rhymers pull request #1
Opened 2022-01-30 12:35 UTC by NORBI0908

Czy mogę prosić o zaakceptowanie? :)

2022-01-30 13:50 UTC, sebastian-tk requested changes
Nazwy stalych powinny byc pisane wielkimi literami oddzielonymi podkreslnikiem ale nie zaczynajace sie od niego wg instrukcji i dokumentacji

https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2022-01-30 15:09 UTC, NORBI0908 commented
Poprawione

2022-01-31 19:52 UTC, sebastian-tk requested changes
Wprowadz wszystkie zmiany z komentarzy

2022-01-31 19:52 UTC, sebastian-tk commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    private static final int ELEVEN = 11;
Zamien ELEVEN na FULL_ARRAY_RHYMERS

2022-01-31 19:52 UTC, sebastian-tk commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	private static final int MINUS_1 = -1;
Zamien nazwe MINUS_1 na EMPTY_ARRAY_RHYMERS

2022-01-31 19:52 UTC, sebastian-tk commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	private static final int TWELVE = 12;
Zamien TWELVE na MAX_QUANTITY_RHYMERS

2022-01-31 19:52 UTC, sebastian-tk commented on src/main/java/edu/kis/vh/nursery/list/IntLinkedList.java
> +    private static final int MINUS_1 = -1;
Zamien MINUS_1 na VALUE_EMPTY_LIST

2022-01-31 19:52 UTC, sebastian-tk commented on src/main/java/edu/kis/vh/nursery/HanoiRhymer.java
> +    private static final int ZERO = 0;
usun zmienna ZERO i zostaw jak bylo tzn
int totalRejected = 0;

2022-02-05 00:21 UTC, sebastian-tk commented on .settings/org.eclipse.m2e.core.prefs
> +activeProfiles=
dodaj plik do .gitignore
zgodnie z punktem mowiacym ze pliki konfiguracyjne wykluczamy

2022-02-05 00:21 UTC, sebastian-tk commented on .settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
dodaj plik do .gitignore
zgodnie z punktem mowiacym ze pliki konfiguracyjne wykluczamy

2022-02-05 00:22 UTC, sebastian-tk commented on .settings/org.eclipse.core.resources.prefs
> +eclipse.preferences.version=1
dodaj plik do .gitignore
zgodnie z punktem mowiacym ze pliki konfiguracyjne wykluczamy

2022-02-05 00:22 UTC, sebastian-tk commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
dodaj plik do .gitignore
zgodnie z punktem mowiacym ze pliki konfiguracyjne wykluczamy

2022-02-05 00:22 UTC, sebastian-tk commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
dodaj plik do .gitignore
zgodnie z punktem mowiacym ze pliki konfiguracyjne wykluczamy

2022-02-05 12:00 UTC, NORBI0908 commented
Zmiany w nazwach naniesione, proszę o akceptację. Plik .gitignore miał być naniesiony w poprzednich zadaniach - nie jest to przedmiotem tego ćwiczenia

2022-02-05 12:10 UTC, merged